server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/db01?useSSL=false&serverTimezone=UTC
    username: root
    password: 951628437q
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: hmdp
    listener:
      simple:
        prefetch: 1
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug